apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  environment: production
namespace: prod
patchesStrategicMerge:
  - deployment.yml
  - service.yml
  - ingress.yml
  - configmap.yml
resources:
  - ../../base