apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  environment: testing
namespace: testing
patchesStrategicMerge:
  - deployment.yml
  - service.yml
  - ingress.yml
  - configmap.yml
resources:
  - ../../base